---
- name: restart gunicorn
  ansible.builtin.systemd:
    name: gunicorn
    state: restarted
    daemon_reload: yes

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
