---
- name: Read and save encoded CA cert content
  ansible.builtin.slurp:
    src: "{{ certificate_path }}/ca.crt"
  register: ca_crt

- name: Read and save encoded kube-proxy cert content
  ansible.builtin.slurp:
    src: "{{ certificate_path }}/kube-proxy.crt"
  register: kube_proxy_crt

- name: Read and save encoded kube-proxy key content
  ansible.builtin.slurp:
    src: "{{ certificate_path }}/kube-proxy.key"
  register: kube_proxy_key

- name: Create kubeconfig for kube-proxy
  ansible.builtin.template:
    src: kubeconfig.j2
    dest: "{{ configs_files_path }}/kube-proxy.kubeconfig"
    mode: '0600'
  vars:
    ca_content: "{{ ca_crt['content'] }}"
    k8s_server_address: https://server.kubernetes.local:6443
    k8s_user: system:kube-proxy
    cluster_name: "{{ k8s_cluster_name }}"
    context_name: "{{ configs_context_name }}"
    client_certificate_content: "{{ kube_proxy_crt['content'] }}"
    client_key_content: "{{ kube_proxy_key['content'] }}"