---
- name: Create kube-scheduler private key
  community.crypto.openssl_privatekey:
    path: "{{ certificate_path }}/kube-scheduler.key"
    size: 4096
    mode: "0600"

- name: Create CSR for kube-scheduler
  community.crypto.openssl_csr:
    path: "{{ certificate_path }}/kube-scheduler.csr"
    privatekey_path: "{{ certificate_path }}/kube-scheduler.key"
    CN: system:kube-scheduler
    O: system:system:kube-scheduler
    C: "{{ C }}"
    ST: "{{ ST }}"
    L: "{{ L }}"
    basic_constraints:
      - CA:FALSE
    extended_key_usage:
      - clientAuth
      - serverAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    subjectAltName:
      - DNS:kube-scheduler
      - IP:127.0.0.1
    create_subject_key_identifier: true


- name: Create kube-scheduler cert
  community.crypto.x509_certificate:
    path: "{{ certificate_path }}/kube-scheduler.crt"
    privatekey_path: "{{ certificate_path }}/kube-scheduler.key"
    csr_path: "{{ certificate_path }}/kube-scheduler.csr"
    provider: ownca
    ownca_path: "{{ certificate_path }}/ca.crt"
    ownca_privatekey_path: "{{ certificate_path }}/ca.key"
    selfsigned_not_after: "+3650d"
    mode: "0600"