---
- name: Create service-accounts private key
  community.crypto.openssl_privatekey:
    path: "{{ certificate_path }}/service-accounts.key"
    size: 4096
    mode: "0600"

- name: Create CSR for service-accounts
  community.crypto.openssl_csr:
    path: "{{ certificate_path }}/service-accounts.csr"
    privatekey_path: "{{ certificate_path }}/service-accounts.key"
    CN: service-accounts
    basic_constraints:
      - CA:FALSE
    extended_key_usage:
      - clientAuth
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    create_subject_key_identifier: true


- name: Create service-accounts cert
  community.crypto.x509_certificate:
    path: "{{ certificate_path }}/service-accounts.crt"
    privatekey_path: "{{ certificate_path }}/service-accounts.key"
    csr_path: "{{ certificate_path }}/service-accounts.csr"
    provider: ownca
    ownca_path: "{{ certificate_path }}/ca.crt"
    ownca_privatekey_path: "{{ certificate_path }}/ca.key"
    selfsigned_not_after: "+3650d"
    mode: "0600"