apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project.name" . }}-deployment
  labels:
    app: {{ include "project.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "project.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "project.name" . }}
    spec:
      containers:
        - name: {{ include "project.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "project.name" . }}-configmap
                  key: allowed-hosts
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "project.name" . }}-secret
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: {{ include "project.name" . }}-secret
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
