apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: parameter-store
  namespace: production
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-north-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: ssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: ssm-secret
            key: secret-access-key
