services:
  db:
    image: "postgres:15-alpine"
    container_name: postgresql-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
#    volumes:
#      - data:/var/lib/postgresql/data
    networks:
      - django-db
  web:
    build: ../..
    container_name: sample-django
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      DATABASE_URL: postgres://user:password@db:5432/db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django-db

networks:
  django-db:
