---
- name: Check if gunicorn systemd service file exists
  stat:
    path: /etc/systemd/system/gunicorn.service
  register: gunicorn_service_file

- name: Configure gunicorn systemd service (only if not exists)
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  when: not gunicorn_service_file.stat.exists
  notify: restart gunicorn

- name: Ensure gunicorn is enabled and started
  systemd:
    name: gunicorn
    enabled: true
    state: started
