---
- name: Copy the kube-scheduler kubeconfig into /var/lib/kubernetes/
  ansible.builtin.copy:
    src: "{{ configs_files_path }}/kube-scheduler.kubeconfig"
    dest: /var/lib/kubernetes/
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Create configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - {src: kube-scheduler.yaml.j2, dest: /etc/kubernetes/config/kube-scheduler.yaml}
    - {src: kube-scheduler.service.j2, dest: /etc/systemd/system/kube-scheduler.service}
  become: true