---
- name: Download Kubernetes binaries
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename }}"
    mode: '0755'
  loop:
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kubectl
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-apiserver
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-controller-manager
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-scheduler
  become: true
