---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  become: true

- name: Start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  become: true