---
- name: Install dependencies for deployment
  ansible.builtin.apt:
    name:
      - nginx
      - python3
      - python3-pip
      - python3-venv
      - libpq-dev
      - build-essential
      - git
    update_cache: true
  become: true
  delegate_to: ami-temp

- name: Upload nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/django
  become: true
  delegate_to: ami-temp

- name: Enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/django
    dest: /etc/nginx/sites-enabled/django
    state: link
    force: yes
  become: true
  delegate_to: ami-temp

- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  delegate_to: ami-temp
