---
- name: Copy CNI network config templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/cni/net.d/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "10-bridge.conf.j2", dest: "10-bridge.conf" }
    - { src: "99-loopback.conf.j2", dest: "99-loopback.conf" }
  become: true

- name: Ensure br-netfilter kernel module is loaded now
  ansible.builtin.modprobe:
    name: br-netfilter
    state: present
  become: true

- name: Persist br-netfilter module across reboots
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: br-netfilter
    create: true
    state: present
  become: true

- name: Ensure net.bridge bridge-nf-call sysctl settings are present
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/kubernetes.conf
    state: present
    reload: true
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
  become: true

