---
- name: Add kube-proxy confs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: kube-proxy-config.yaml.j2, dest: /var/lib/kube-proxy/kube-proxy-config.yaml }
    - { src: kube-proxy.service.j2, dest: /etc/systemd/system/kube-proxy.service }
    - { src: "{{ configs_files_path }}/kube-proxy.kubeconfig", dest: /var/lib/kube-proxy/kubeconfig}
  become: true