apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-sample
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameter-store
    kind: SecretStore
  target:
    name: sample-django-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: /task3_db_username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /task3_db_password
    - secretKey: DB_NAME
      remoteRef:
        key: /task3_db_name
    - secretKey: SECRET_KEY
      remoteRef:
        key: /task3_secret_key
