apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: dev-read-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-secrets-binding
  namespace: production
subjects:
  - kind: Group
    name: eks:devs
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-read-secrets
  apiGroup: rbac.authorization.k8s.io
