apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "project.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuerName }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.certManager.enabled }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ include "project.name" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "project.name" . }}-service
                port:
                  number: 80
