apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "project.name" . }}-sa
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-{{ include "project.name" . }}-secret
  namespace: production
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    resourceNames: [ "{{ include "project.name" . }}-secret","{{ include "project.name" . }}-configmap" ]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-{{ include "project.name" . }}-sa
  namespace: production
subjects:
  - kind: ServiceAccount
    name: {{ include "project.name" . }}-sa
    namespace: production
roleRef:
  kind: Role
  name: read-{{ include "project.name" . }}-secret
  apiGroup: rbac.authorization.k8s.io
