apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "project.name" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: {{ include "project.name" . }}-storage-class
